// バックエンドアプリ外のエラー用
export const failureCallBack = (error) => {
  alert(error);
}
